### ISSUE TITLE
Is there a way to have both contri org-toc and this toc?

### ISSUE THREAD

**Issue by LeoUfimtsev** [snosov1/org-toc#8]
As subject suggests. I'd like to use both packages, but is there a way to do so?

**Comment by LeoUfimtsev** [comment]
The suggested solution from the read-me doesn't seem to work?

I added the following to my init:
    (if (require 'org-toc nil t)
        (add-hook 'org-mode-hook 'org-toc-enable)
      (warn "org-toc not found"))

But toc generation doesn't work and my other packages break. Meh.

**Comment by snosov1** [comment]
Hey, there!

Yeah, I absolutely agree, something needs to be done about this conflict, but I haven't yet figured out a "good enough" way to handle this. 

I'll probably ask MELPA maintainer for an advice. He was very helpful to me in the past and he's obviously much more proficient on the subject. Stay tuned!

**Comment by LeoUfimtsev** [comment]
I downloaded your code, did a find & replace. I replaced all org-toc with org-dyn-toc and things work for me. I guess it's a bit tedious to do it in the long run, but works for now.  (dyn as in dynamic).

**Comment by snosov1** [comment]
Steve suggested to rename the package on MELPA and call it a day. So, now the mode is called `toc-org`. Please, update your configuration file, that should solve it.

**Comment by LeoUfimtsev** [comment]
:+1:
